### ISSUE TITLE
No ppc64le or s390x builds?

### ISSUE THREAD

**Issue by christopher-horn** [redhat-developer/devspaces-chectl#125]
Developer Workspaces is supported on both s390x and ppc64le platforms but packages for dsc on those platforms appear to be missing.

**Comment by nickboldt** [comment]
Correct. This is because there has so far been no request to install Dev Spaces on s390x or ppc64le FROM a machine running that arch.

However we have been asked to build dsc to run on these arches:

* linux-x64
* darwin-x64
* darwin-arm64
* win32-x6

https://github.com/redhat-developer/devspaces-chectl/commit/ac3460aa7d2c9aeecf105d665588703c3d74e9d4#diff-e9b3a39d3e0e884da476079e04bc22dfb38866c1586bb09364cf65ece255ebc5R20

Are you saying you have a use case for logging into a machine running s390x aor ppc64le, and then using that to communicate with an OpenShift cluster that is also running s390x or ppc64le?

If so, please open an issue here: https://issues.redhat.com/browse/CRW

**Comment by christopher-horn** [comment]
Yes, I did, I ended up building it myself on s390x.  But I will open issue, I think there should be builds for all the supported architectures.

**Comment by nickboldt** [comment]
Thanks for reaching out, and apologies for not seeing his issue sooner -- we only watch for issues in https://github.com/eclipse/che/issues/ and https://issues.redhat.com/browse/CRW so I only happened to see your question accidentally. :D
